version: '3.5'

networks:
  library-backend:

services:
  library-db:
    container_name: library-db
    image: mysql:5.7
    restart: always
    networks:
      - library-backend
    environment:
      - MYSQL_ROOT_PASSWORD=secret-pass
      - MYSQL_DATABASE=library
      - MYSQL_USER=library
      - MYSQL_PASSWORD=LNoa5eelBYdCJpW6

  library-app:
    container_name: library-app
    ports:
      - '8080:8080'
    networks:
      - library-backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - library-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://library-db:3306/library
      SPRING_DATASOURCE_USERNAME: library
      SPRING_DATASOURCE_PASSWORD: LNoa5eelBYdCJpW6
