version: '3.5'

networks:
  backend:

services:
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=library
      - MYSQL_USER=library
      - MYSQL_PASSWORD=LNoa5eelBYdCJpW6
    networks:
      - backend

  app-server:
    image: library_spring_image
    ports:
    - '8080:8080'
    networks:
      - backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/library?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: library
      SPRING_DATASOURCE_PASSWORD: LNoa5eelBYdCJpW6
